---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-kibana
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: cook-my-list
      app.kubernetes.io/svc: ngrok-kibana
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        cook-my-list/role: infra
        app.kubernetes.io/svc: ngrok-kibana
    spec:
      containers:
      - image: wernight/ngrok:latest
        imagePullPolicy: IfNotPresent
        name: ngrok
        envFrom:
          - configMapRef:
              name: ngrok

        env:
          - name: NGROK_SUBDOMAIN
            value: kibana-ci-butler

          - name: NGROK_DEBUG
            value: "true"

          - name: NGROK_BINDTLS
            value: "both"

          - name: NGROK_HOSTNAME
            value: "kibana-ci-butler.ngrok.io"

          - name: NGROK_PORT
            value: kibana-kibana.ci-butler-data:5601
