name: 🚢 K8S Docker Image

defaults:
  run:
    working-directory: ./scraper-engine

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: K8S Docker Image (Kubernetes Deployment)
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gabrielfalcao/cook-my-list
        dockerfile: scraper-engine/Dockerfile
        path: scraper-engine
        # tag_with_ref: false  # prevent pushing "latest" tag
        tag_with_sha: true
        tags: "${{ github.sha }}"
